# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af0d56eb58c86806eda0e22ec7aff4357d1456c5eb0ac71d4b805686a9b18630ddc2fc56934fbed584df35c4f83e01f38ad854cb4dffd7e93af78149b02e2e0c

test:
  secret_key_base: 5401ab15c720e074b1e95de83cc6a0b453153d0de27ded7322540813f0ac66906e4cb531e47a3ce02edbc67bf7c23ea46d9d005cd9c52a2fe755d5ed24babd92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
